-- ─────────────────────────────────────────────────────────────
-- Mila Agent: Proactive Insights & Action Audit Trail
-- ─────────────────────────────────────────────────────────────

-- ── mila_insights: Proactive alerts generated by the background agent ──
-- Stores anomaly detections, trend alerts, and recommendations
-- generated by the daily Edge Function scan.
CREATE TABLE IF NOT EXISTS mila_insights (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    outlet_code   TEXT,
    severity      TEXT NOT NULL DEFAULT 'info' CHECK (severity IN ('critical', 'warning', 'info')),
    category      TEXT NOT NULL DEFAULT 'general', -- e.g. 'anomaly', 'trend', 'compliance', 'recommendation'
    title         TEXT NOT NULL,
    description   TEXT NOT NULL,
    metadata      JSONB DEFAULT '{}',
    -- Actionable recommendation
    recommendation TEXT,
    -- Whether the user has seen/dismissed this insight
    is_read       BOOLEAN DEFAULT FALSE,
    is_dismissed  BOOLEAN DEFAULT FALSE,
    -- When the insight was generated
    created_at    TIMESTAMPTZ DEFAULT now(),
    -- Which scan generated this (for dedup)
    scan_batch_id TEXT
);

-- Indexes for fast queries
CREATE INDEX IF NOT EXISTS idx_mila_insights_user ON mila_insights(user_id);
CREATE INDEX IF NOT EXISTS idx_mila_insights_unread ON mila_insights(user_id) WHERE is_read = false;
CREATE INDEX IF NOT EXISTS idx_mila_insights_severity ON mila_insights(severity);
CREATE INDEX IF NOT EXISTS idx_mila_insights_created ON mila_insights(created_at DESC);

-- RLS: Users can only see their own insights
ALTER TABLE mila_insights ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own insights"
    ON mila_insights FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can update own insights"
    ON mila_insights FOR UPDATE
    USING (auth.uid() = user_id);

-- Service role (Edge Functions) can insert/delete all
-- (Service role bypasses RLS by default)


-- ── mila_actions: Audit trail of all agent actions ──
-- Every time Mila executes a tool (log entry, generate report, etc.)
-- it's recorded here for accountability.
CREATE TABLE IF NOT EXISTS mila_actions (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    actor_name    TEXT,
    actor_role    TEXT,
    -- The tool that was called
    tool_name     TEXT NOT NULL,
    tool_args     JSONB DEFAULT '{}',
    -- Result
    result        JSONB DEFAULT '{}',
    success       BOOLEAN DEFAULT true,
    -- Context
    outlet_code   TEXT,
    conversation_id TEXT, -- Links to the chat session
    created_at    TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_mila_actions_user ON mila_actions(user_id);
CREATE INDEX IF NOT EXISTS idx_mila_actions_tool ON mila_actions(tool_name);
CREATE INDEX IF NOT EXISTS idx_mila_actions_created ON mila_actions(created_at DESC);

ALTER TABLE mila_actions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own agent actions"
    ON mila_actions FOR SELECT
    USING (auth.uid() = user_id);


-- ── Helper function: Get unread insight count for a user ──
CREATE OR REPLACE FUNCTION get_unread_insight_count(p_user_id UUID)
RETURNS INTEGER
LANGUAGE sql
SECURITY DEFINER
AS $$
    SELECT COUNT(*)::INTEGER
    FROM mila_insights
    WHERE user_id = p_user_id
      AND is_read = false
      AND is_dismissed = false;
$$;


-- ── Helper function: Mark insight as read ──
CREATE OR REPLACE FUNCTION mark_insight_read(p_insight_id UUID, p_user_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
AS $$
    UPDATE mila_insights
    SET is_read = true
    WHERE id = p_insight_id AND user_id = p_user_id
    RETURNING true;
$$;
